[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "demo"
version = "0.1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = {version = "0.2.77"}
